public class GenericConstants {
    
    //Constants for Lead and Opportunity transfer Api
    Public static final String IM_TRANSFER = 'IM Transfer';
    Public static final String FREELANCER_TRANSFER ='Freelancer Transfer';
    Public static final String OPPORTUNITY_ID = '006';
    Public static final String LEAD_ID ='00Q';
    Public static final String Showroom_user_Id ='a1F';
    Public static final String LEAD_OPPORTUNITY_TRANSFER = 'Lead_Opportunity_Transfer';
    Public static final String IM_TRANSFER_CHECK ='IM Transfer Check';
    Public static final String ENABLED_CHECK ='Enabled';
    Public static final String PRONTO_SIGNUP_SOURCE ='Pronto Paint';
    Public static Final String SETUP_CONFIG_OPEN_STATUS ='Open';
    Public static Final String SETUP_CONFIG_CLOSED_STATUS ='Closed';
    Public static Final String SETUP_CONFIG_FAILED_STATUS ='Failed';
    Public static Final String TELECALLER_TRANSFER ='Telecaller Transfer';
    Public static Final String NIMBUS_TRANSFER ='Nimbus Transfer';
    Public static final String DOOWUP_TRANSFER ='Doowup Transfer';
    Public static final String ROLE_ProductConsultant ='Product Consultant';
    Public static final String ROLE_TeleCallerAgent ='Tele Caller Agent';
    Public static final String ROLE_PreSalesFreelancer ='Pre-Sales Freelancer';
    public static final String LeadSource_FB_Lead_Form='FB Lead Form';
   
    
    //Constants for AddressInfo Api
    Public static final String PROPERTY_NAME = 'Name';
    public static final String PROPERTY_PLACEID= 'PlaceId';
    public static final String PROPERTY_LEADID ='LeadId';
    Public static final String PROPERTY_GOOGLE_VERIFIED ='Google Verified';
    Public static final String PROPERTY_MANUALLY_VERIFIED ='Manually Verified';
    Public static final String PROPERTY_GOOGLE_NOT_VERIFIED  ='Google Not Verified';
    Public static final String PROPERTY_TYPE_INPUT ='Type';
    Public static final String PROPERTY_LAT='lat';
    Public static final string PROPERTY_LNG='lng';
    Public static final String PROPERTY_CITY ='City';
    Public static final String PROPERTY_LOCALITY ='Locality';
    Public static final String PROPERTY_LANDMARK ='Landmark';
    Public static final String PROPERTY_STREET = 'Street';
    Public static final String PROPERTY_STATE = 'State';
    Public static final String PROPERTY_MAPLINK = 'Map Link';
    Public static final String PROPERTY_LATLNG = 'latlng';
    Public static final String PROPERTY_PROP_TYPE ='Property_Type__c';
    Public static final String PROPERTY_USERNAME = 'UserName';
    Public static final String PROPERTY_POSTALCODE ='Postal Code';
    Public static final String PROPERTY_VERIFYTYPE_GOOGLE='Google';
    Public static final String PROPERTY_VERIFYTYPE_UNVERIFIED ='Unverified';
    
    //Constants for IMAttendance 
    Public static final String ENDPOINT_DARWIN_AUTH_TOKEN ='DarwinBOX Auth Token';
    Public static final String DARWINBOX_ACCESS_TOKEN ='access_token';
    Public static final String ENDPOINT_DARWIN_IRM_ATTENDANCE='DarwinBOX IRM Attendance_API';
    
    
    Public static final String LEAD_RELANDED_SOURCE = 'LeadSource';
    
    //Constants for lead status and substatus 
    Public static final String LEAD_FRESH_STATUS = 'Fresh Lead';
    Public static final String LEAD_DEAD_STATUS  ='Dead Lead';
    Public static final String LEAD_NEW_SUBSTATUS ='New';
    Public static final String LEAD_RELANDED_SUBSTATUS ='Re-Landed';
    Public static final String LEAD_APPOINTMENT_SUCCESSFUL ='Appointment Successful';
    Public static final String LEAD_APPOINTMENT_UNSUCCESSFUL  =  'Appointment Unsuccessful';
    Public static final String LEAD_APPOINTMENT_CANCELLED = 'Appointment Cancelled';
    Public static final String LEAD_SUBSTATS_FOLLOWUP_LATER_CX ='Follow-up Later (Cx requested)';
    Public static final String LEAD_SUBSTATS_FOLLOWUP_LATER_NOT_MENTION ='Follow-up Later (Not mentioned)';
    
    Public static final String LEAD_PRE_APPOINTMENT_STATUS ='Pre-Appointment';
    Public static final String LEAD_WHATSAPP_PRE_APPOINTMENT_STATUS ='WhatsApp Pre-Appointment';
    Public static final String LEAD_APPOINTMENT_FIXED_STATUS = 'Appointment Fixed';
    Public static final String LEAD_SUBSTATUS_UNVERIFIED = 'Unverified';
    Public static final String LEAD_SUBSTATUS_CUST_ONLINE ='Customer Online';
    Public static final String LEAD_SUBSTATUS_COMMERCIAL_REQUIREMENT ='Commercial requirement';
    Public static final String LEAD_SUBSTATUS_QUALIFICATION_CONSTRAINTS='Qualification Constraints(Budget/Requirements)';
    Public static final String DEAD_LEAD_REASON_COMMERCIAL_INTERIOR_REQUIREMENT ='Commercial interiors requirement';
    
    
    Public static final String LEAD_NOT_ACTIVELY_PURSUED_STATUS='Not actively pursued';
    Public static final String MAIN_ORDER ='Main_Order__c';
    Public static final String LEAD_SIGNUP_SOURCE='signup_source';
    Public static final String LEAD_SOURCE_OFFLINE='Homelane Broker/Channel Partner';
    Public static final String LEAD_TRANSFERRED_TO_DOOWUP_STATUS='Transferred to Doowup';
    Public static final String SCOPE_OF_WORK ='Scope_Of_Work__c';
    Public static final String MANUAL_LEAD_CREATION = 'Manual Lead Creation';
    Public static final String SF_USER_EMAIL ='SF_User_Email';
    Public static final String PROFILE_WTA = 'WTA Profile';
    Public static final String PROFILE_WTM ='WTM Profile';
    Public static final String LEAD_CREATED_BY_SFWT_USER = 'SF-WT Users';
    Public static final String LEAD_CREATED_BY_SF_OTHER = 'SF-Other Users';
    Public static final String SOBJECT_ACCOUNT = 'Account__c';
    Public static final String LEAD_CREATED_BY_WEBSITE ='Website';
    Public static final String SUBORDER_ISDESIGNREQUIRED ='isDesignRequired';
    Public static final String SF_ACCOUNT_ID ='SF_Account_Id';
    Public static final String LEAD_DOOWUP = 'Doowup';
    Public Static final String LEAD_HOMELANE = 'Homelane';
    Public static final String CLUSTER_BRAND_DOOWUP ='Doow up';
    PUBLIC STATIC FINAL STRING CLUSTER_BRAND_HOMELANE ='Homelane';
    public static final string PRODUCT_CONSULTANT_ROLE ='Product Consultant';
    
    
    Public Static final String SQUADIQ_SENT_TOSQUADIQ ='Sent to SquadIQ';
    Public static final String SQUADIQ_PROCESSED_BY_SQUADIQ ='Processed by SquadIQ';
    Public static final String  NOT_A_NIMBUS_LEAD ='Not a Nimbus Lead';
    Public static final String FAILED_SENDING_TO_NIMBUS  ='Failed Sending to Nimbus';
    Public static final String SENT_TO_NIMBUS ='Sent to Nimbus';
    Public static final String ASSIGNED_TO_NIMBUS ='Assigned to Nimbus';
    Public static final String PROCESSED_BY_NIMBUS ='Processed by Nimbus';
    Public static final String NIMBUSSTATUSDU000 ='DU000';
    Public static final String FAILED_SENDING_NIMBUS ='Failed Sending to Nimbus';
    
    public static final String Lead_Source_HomeLane ='HomeLane';
    public static final String Lead_Source_HomeLane_DeadLead ='HomeLane_Dead Lead';
    public static final String Lead_Source_HomeLane_Opportunity='HomeLane_Opportunity';
    public static final String Lead_Source_HomeLane_ScopeUndetermined='HomeLane_Scope Undetermined';
    public static final String Lead_Source_Offline_DeadLead ='Offline Dead Lead';
    
    public static final String HomeLane_Nimbus ='HomeLane_Nimbus';
    public static final String Nimbus_Hindi_Transfer ='Nimbus Hindi Transfer';
    public static final String HomeLane_Nimbus_Kannada ='HomeLane_Nimbus_Kannada';
    public static final String Nimbus_Tamil='HomeLane_Nimbus_Tamil';
    public static final String Nimbus_Telugu_Transfer='Nimbus Telugu Transfer';
    public static final String Nimbus_Doowup_Opp_Transfer='Nimbus Doowup Opp Transfer';
    public static final String Whatsapp_Fresh_Lead ='WhatsApp Fresh Lead';
    
    public static final string  LEAD_SOURCE_FACEBOOKAD ='Facebook Ad';
    public static final string TEST_EVENT_CODE ='test_event_code';
    //user_data event_name event_time": 1681364569,
            //"action_source": "website",
    public static final string USER_DATA ='user_data';
    public static final string CUSTOM_DATA ='custom_data';
    public static final string Event_Name ='event_name';
    public static final string Event_Source ='event_source';
    public static final string Lead_Event_Source ='lead_event_source';
    public static final string Event_Time ='event_time';
    public static final string Action_Source ='action_source';
    public static final String System_Generated ='system_generated';
    
    public static final string Opp_Payment_Stage_A_Reached ='Payment Stage A Reached';
    public static final String Lead_Status_whatsAPP_Fresh ='WhatsApp Fresh Lead';
    
    public static final string Doowup_PreSales_Role ='Doowup Presales';
    
    public static final String Doowup_Presales_Transfer ='Doowup Presales Transfer'   ; 
    public static final String Nimbus_DL_Offline_Transfer ='Nimbus DL Offline Transfer';
    public static final String Nimbus_DL_Digital_Transfer ='Nimbus DL Digital Transfer';
    public static final String Offline_Relanded_Transfer ='Offline Relanded Transfer';
    public static final String Sales_Team_Redialing= 'Sales Team Redialing';
    public static final Integer Lead_Gold_Plus_Score =8;
    public static final Integer Lead_Gold_Score=7;
    public static final Integer Lead_Silver_Score=6;
    public static final Integer  Lead_Bronze_Score =3;
    public static final Integer  Lead_Silver_Minus_Score=5;
    
    public static final Integer Lead_Bronze_Plus_Score= 4;
    
    public static final String All_Lead_Sources ='All';
    Public static final String Customer_PreAppt_Meeting_Source ='Customer';
    Public static final String Green_Lead_Gold_Plus ='Gold+';
    Public static final String Green_Lead_Gold ='Gold';
    public static final String Green_Lead_Silver ='Silver';
    public static final String Green_Lead_Bronze ='NA';
    
    public static final String Central_Team_Agent='Central Team Agent';
    public static final String Inside_Sales_Team_Agent='Inside Sales Agent';
    public static final String Green_Channel_Campaign ='Green Channel';
    public static final String Inside_Sales_Campaign ='Inside Sales';
    public static final String Outskirts_City='Outskirts';
    public static final string IM_Classification_Transfer= 'IM Classification';
    public static final string IM_Class_Gold ='Gold';
    public static final string IM_Class_Silver ='Silver';
    public static final string IM_Class_Bronze ='Bronze';
    
    public static final string Gold_Plus_RECID= 'Gold Plus Score Leads';
    public static final string Gold_RECID  = 'Gold Score Leads';
    public static final string Silver_RECID = 'Silver Score Leads';
    public static final string GOLD_CLASSIFICATION  = 'Gold Classification';
    public static final string SILVER_CLASSIFICATION = 'Silver Classification';
    public static final string Silver_Minus_RECID = 'Silver Minus Score Leads';
    public static final string Bronze_Plus_RECID ='Bronze Plus Score Leads';
    public static final string Lead_Budget_4L ='1.5L - 4L';
    public static final string Lead_Budget_1L ='Upto 1.5L';
    public static final string Lead_Budget_NA1 ='Cx did not disclose';
    public static final string Lead_Budget_NA2 ='Cx didn\'t disclose';
    public static final string Property_Status_Renovation ='Renovation';
    public static final string Property_JSON ='PropertyJson';
    public static final string Sign_Up_WhatsApp_Haptik='WhatsAppHaptik';
    
    public static final string WhatsApp_Haptik_IM_Assignment='WhatsApp Haptik IM Assignment';
     public static final string WhatsApp_Haptik_InsideSales_Assignment ='WhatsApp Haptik InsideSales Assignment';
    public static final string Green_Channel_IM_Assignment='Green Channel IM Assignment';
    public static final string FB_Lead_Form = 'FB Lead Form';
    public static final string LinkedIn_Lead_Form='LinkedIn Lead Form';
    public static final String WhatsApp_Pre_Appointment = 'WhatsApp Pre-Appointment';
    
    public static final String LD_City_Chennai='Chennai';
    public static final String LD_City_Hyderabad='Hyderabad';
    public static final String LD_City_Bengaluru='Bengaluru';
    public static final String LD_City_Kolkata='Kolkata';
    public static final String LD_City_Mysore='Mysore'; 
    public static final String LD_City_Ranchi='Ranchi'; 
    public static final String LD_City_Guwahati='Guwahati'; 
    public static final String LD_City_Coimbatore='Coimbatore';
    public static final String LD_City_NewDelhi='New Delhi';
    public static final String LD_City_Gurgaon='Gurgaon';
    public static final String LD_City_Noida='Noida';
    public static final String LD_City_Ghaziabad ='Ghaziabad';
    public static final String LD_City_Ahm ='Ahmedabad';
    public static final String LD_City_Thane ='Thane';    
    public static final String LD_City_Bhubaneswar = 'Bhubaneswar';
    public static final String LD_City_Jaipur = 'Jaipur';
    public static final String LD_City_Kochi = 'Kochi';
    public static final String LD_City_Lucknow = 'Lucknow';
    public static final String LD_City_Madurai = 'Madurai';
    public static final String LD_City_Nagpur = 'Nagpur';
    public static final String LD_City_Salem = 'Salem';
    public static final String LD_City_Surat = 'Surat';
    public static final String LD_City_Trichy = 'Trichy';
    public static final String LD_City_Visakhapatnam = 'Visakhapatnam';

    
    public static final String Property_Type ='Property_Type__c';
    public static final String Inside_Sales_Transfer ='Inside Sales Transfer';
    //public static final String Green_Lead_Gold_Plus ='Gold+';
    public static final String Green_Lead_Silver_Minus='Silver-';
    public static final String Green_Lead_Bronze_Plus ='Bronze+';
    public static final String Nimbus_Relanded_Transfer ='Nimbus Relanded Transfer';
    public static final String Lead_Requested_By ='requestedBy';
    public static final String Roster ='Roster';
    public static final String LD_City_Pune='Pune';
    public static final String LD_City_Mumbai='Mumbai';
    public static final String  Update_Property_Type='updatePropertyTypeOnly';
     public static final String HomeLaneLuxeLeadForm='HomeLaneLuxeLeadForm';
    public static final String Property_RecordId ='Property';
     public static final String Showroom_Type ='Showroom';
    public static final String Dealer_Showroom_Type ='Dealer Showroom';
    public static final String Brand_Cubico ='Cubico';
    public static final String Cubico_Transfer ='Cubico Transfer';
     public static final String INSIDE_SALES_SWITCH_BATCH = 'InsideSales Switching Batch';
    public static final String DEAD_LEAD_DFN_ASSIGNMENT ='Dead Lead DFN Assignment';    
    public static final String NIMBUS_DOOWUP_OFFLINE_TRANSFER ='Nimbus Doowup Offline Transfer';
    public static final String NIMBUS_DOOWUP_HL_TRANSFER ='Nimbus Doowup HL Transfer';
    public static final String HomeLane_Nimbus_Doowup_Offline ='Doowup Offline';
    public static final String NIMBUS_HL_MISSEDCALL_TRANSFER = 'Nimbus HL Missed Call Transfer';
    public static final String LEAD_SOURCE_OFFLINE_ADS = 'Offline Ads';
    public static final String SIGNUP_SOURCE_V2L = 'V2L';
    public static final String Brand_Wrapzap ='Wrapzap';
    public static final String Wrapzap_Transfer ='Wrapzap Transfer';
    public static final string Lead_Budget_8L ='4L - 8L';
    public static final string Sign_Up_Source_EstimateFlow = 'Estimate Flow';
    public static final string Property_Status_RentOut = 'Rent Out';
    public static final string LEAD_SUBSTATUS_OTHER_CATEGORY_REQUIREMENT = 'Other Category Requirements';
    Public static final String DEAD_LEAD_REASON_LAMINATE_CHANGE ='Laminate Change';
    Public static final String OFFLINE_LEAD_SOURCE = 'Broker/Channel Partner';
    Public static final String CLUSTER_TYPE_A = 'A';   
    Public static final String SINGLE_INPUT_FIELD = 'Single Input Field'; 
    Public static final String Single_Input_InsideSales_Assignment = 'Single Input InsideSales Assignment';
    Public static final String TRANSFER_HL_DEADLEAD_ASSIGNMENT = 'Transfer HL Dead Lead Assignment';
    Public static final String DOOWUP_DFN_TRANSFER_ASSIGNMENT = 'Doowup DFN Transfer Assignment';
    Public static final String DOOWUP_FOCO_TRANSFER_ASSIGNMENT = 'Doowup FOCO Transfer Assignment';
    
    public static final String Globiva_Offline_RL_Transfer = 'Globiva Offline RL Transfer';
    public static final String Globiva_Offline_PB_Transfer = 'Globiva Offline PB Transfer';
    public static final String Globiva_Relanded_Transfer = 'Globiva Relanded Transfer';
    public static final String Globiva_Feedback_Digital_Transfer = 'Globiva Feedback Digital Transfer';
    public static final String Globiva_Digital_North_Transfer = 'Globiva Digital North Transfer';
    public static final String Globiva_Digital_South_Transfer = 'Globiva Digital South Transfer';
    public static final String Globiva_Digital_East_Transfer = 'Globiva Digital East Transfer';
    public static final String Globiva_Digital_West_Transfer = 'Globiva Digital West Transfer';
    public static final String Globiva_Digital_Centre_Transfer = 'Globiva Digital Centre Transfer';
    public static final String GLOBIVA = 'Globiva';
    public static final String LEADSOURCE_WEBINAR = 'HomeLane Webinar July 2024';
    public static final String RELANDED_SOURCE_WEBINAR = 'Webinar Tally Form';
	public static final String LEAD_SUBSTATUS_WEBINAR = 'Re-Activated by Webinar';
    public static final String LEADSOURCE_HL_UNSERVICEABLE  = 'HomeLane_Unserviceable';
    public static final String FB_EVENT_LEADCREATION  = 'Lead WebCAPI';
}