@isTest(SeeAllData = TRUE)
private class LeadPushToAmeyoController_Test{
    
    /*static testMethod void checkCallout1(){
        Test.startTest();
       // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorAmeyo());
        
         // Call the method that invokes a callout
            LeadPushToAmeyoController.pushToAmeyo('updateContactSessionId-Invalid','test','Test');
         Test.stopTest();
    }
    static testMethod void checkCallout2(){
        Test.startTest();
       // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorAmeyo());
        
         // Call the method that invokes a callout
            LeadPushToAmeyoController.checkSessionId('valid Session');
         Test.stopTest();
    }
    static testMethod void checkCallout3(){
        Test.startTest();
       // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorAmeyo());
        
         // Call the method that invokes a callout 
            LeadPushToAmeyoController.getAmeyoSessionId('CustomerManager1','passwoed');
         Test.stopTest();
    }
    static testMethod void checkCallout4(){
        Test.startTest();
       // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorAmeyo());
        
         // Call the method that invokes a callout 1234567865
            LeadPushToAmeyoController.PushLeadToAmeyo('updateContactlead-Invalid','test');
         Test.stopTest();
    }
    static testMethod void checkCallout5(){
        Test.startTest();
       // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorAmeyo());
        
         // Call the method that invokes a callout
            LeadPushToAmeyoController.PushLeadToAmeyo('1234567865','test');
         Test.stopTest();
    }
    static testMethod void checkCallout6(){
        Test.startTest();
       // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorAmeyo());
        
         // Call the method that invokes a callout
            LeadPushToAmeyoController.pushToAmeyo('d224-5ad8bd34-ses-CustomerManager-vc2JkjaF-14','Test','test');
         Test.stopTest();
    }*/
}