public class LeadConstants {
    Public static final String SITE_VISIT_APPOINTMENT_TYPE = 'Site Visit';
    Public static final String OFFICE_VISIT_APPOINTMENT_TYPE = 'Office Visit';
    Public static final String RESIDENCE_VISIT_APPOINTMENT_TYPE = 'Residence Visit';
    Public static final String LEAD_STATUS_APPOINTMENT_FIXED = 'Appointment Fixed';
    Public static final String LEAD_SUB_STATUS_APPOINTMENT_FIXED = 'Appointment Fixed';
    Public static final String VALUE_YES = 'Yes';
    Public static final String VALUE_NO = 'No';
    
}