public class MasterConstants {
    Public Static final String TYPE_SHOWROOM = 'ShowRoom';
    Public Static final String TYPE_BUILDER = 'Builder';
    Public Static final String DEALER_SHOWROOM = 'Dealer Showroom';
    Public Static final String DATABASE_TYPE_UNVERIFIED = 'Unverified';
    Public Static final String VERIFICATION_STATUS_GOOGLE_NOT_VERIFIED = 'Google Not Verified';
    Public Static final String DATABASE_TYPE_GOOGLE = 'Google';
    Public Static final String VERIFICATION_STATUS_GOOGLE_VERIFIED = 'Google Verified';

}