public class RecursiveTriggerHandlerLead{
     public static Boolean isFirstTime = true;
     public static Boolean smsSend = false;
     
    //used for leadRecursion handler
    public static boolean isAfterUpdateLead = false;
    public static boolean isBeforeUpdateLead = false;
    public static Decimal beforeCount = 0;
    public static Decimal afterCount = 0;
    Public static boolean bCallToOzonetel = true;
    Public static boolean bCallOutGroupB = true;
    Public static boolean bNotactivelypursued = true;
    Public static boolean isEmailchangeExecutingFirstTime = True;    
    public static decimal cubicoCount =0;
    public static decimal doowupCount =0;
    public static decimal wrapzapCount =0;
}